services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    expose:
      - 8080
    depends_on:
      - db
    volumes:
      - web_app_local_files:/web_app
    container_name: local-community-web
  db:
    image: postgres:alpine
    container_name: local-community-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
  web_app_local_files:
    driver: local
    driver_opts:
      type: none
      device: ./
      o: bind
