default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { "db" } %>

development:
  primary:
    <<: *default
    database: empty_development
  authentication:
    <<: *default
    database: authentication_development
    migrations_paths: db/authentication_migrate
  documents_generator:
    <<: *default
    database: documents_generator_development
    migrations_paths: db/documents_generator_migrate

test:
  primary:
    <<: *default
    database: empty_test
  authentication:
    <<: *default
    database: authentication_test
    migrations_paths: db/authentication_migrate
  documents_generator:
    <<: *default
    database: documents_generator_test
    migrations_paths: db/documents_generator_migrate

production:
  primary:
    <<: *default
    database: empty_production
  authentication:
    <<: *default
    database: authentication_production
    migrations_paths: db/authentication_migrate
    username: authentication_user
    password: <%= ENV["AUTHENTICATION_DATABASE_PASSWORD"] %>
  documents_generator:
    <<: *default
    database: documents_generator_production
    migrations_paths: db/documents_generator_migrate
    username: documents_generator_user
    password: <%= ENV["DOCUMENTS_GENERATOR_DATABASE_PASSWORD"] %>