default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db

development:
  primary:
    <<: *default
    database: empty_development
  authentication:
    <<: *default
    database: authentication_development
    migrations_paths: db/authentication_migrate

test:
  primary:
    <<: *default
    database: empty_test
  authentication:
    <<: *default
    database: authentication_test
    migrations_paths: db/authentication_migrate

production:
  primary:
    <<: *default
    database: empty_production
  authentication:
    <<: *default
    database: authentication_production
    migrations_paths: db/authentication_migrate
    username: authentication_user
    password: <%= ENV["AUTHENTICATION_DATABASE_PASSWORD"] %>
